sudo: required
services:
  - docker

before_install:
  - docker build -t daeril/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run daeril/react-test npm test -- --coverage

after_success:
  - docker build -t daeril/multi-client ./client
  - docker build -t daeril/multi-nginx ./nginx
  - docker build -t daeril/multi-server ./server
  - docker build -t daeril/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push daeril/multi-client
  - docker push daeril/multi-nginx
  - docker push daeril/multi-server
  - docker push daeril/multi-worker
